### ISSUE TITLE
The `profile` column in the `okta_application` table does not contain any information

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-okta#38]
**Describe the bug**
For any rows from the `okta_application` table, the `profile` column never has data

**Steampipe version (`steampipe -v`)**
v0.10.0

**Plugin version (`steampipe plugin list`)**
v0.1.0

**To reproduce**
Run `select name, profile from okta_application` while having at least 1 application

**Expected behavior**
The `profile` column should have data or not be defined if the API doesn't return any data for it

**Additional context**
`Application` type - https://github.com/okta/okta-sdk-golang/blob/master/okta/application.go#L35

**Comment by c0d3r-arnab** [comment]
The following response was received from the OKTA support team:
```
The Profile property is designed for the ListApplicationUsers(), UpdateApplicationUser(), GetApplicationUser() and AssignUserToApplication() methods, which all of them are making an API call to the {{url}}/api/v1/apps/{{appId}}/users/{{userId}} endpoint.
The {{url}}/api/v1/apps endpoint does not contain any property called 'Profile' as it is only available for users.
```

As a result, it has been decided to remove `profile` from the list of columns available for the table.
