### ISSUE TITLE
profile data not available in okta_application table

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-okta#57]
**Describe the bug**
With the removal of the 'assigned_groups' field in the 'okta_application' table the profile data we used to have access to is no longer available.  

**Steampipe version (`steampipe -v`)**
Example: v0.11.2

**Plugin version (`steampipe plugin list`)**
Example: v0.3.0

**To reproduce**
With the 0.2 version of the plugin we were able to run:
```
Begin transaction;
create temp table if not exists t1 on commit drop as select jsonb_array_elements(assigned_groups)#>>'{id}' as groupid, jsonb_array_elements(assigned_groups)#>>'{profile,samlRoles}' as roles from okta.okta_application where filter = 'group.id eq "xxxxxxxxxxxx"' AND label = 'foo';
create temp table if not exists t2 on commit drop as select name,id from okta.okta_group where id in (select groupid from t1);
select t2.name,t1.groupid, jsonb_array_elements_text(t1.roles::jsonb) as samlRole from t1,t2 where t1.groupid = t2.id;
commit;
```
which would give us the first 20 group assignments (see issue #47) for an app with the associated samlRoles assigned to each group
Note: with issue #40 fixed we dont have to use the "where filter" clause anymore (we can just do "where id = ....")

**Expected behavior**
Some way yo access the profile.SamlRoles data in the okta_application table or okta_app_assigned_group (or maybe a whole other table)

**Additional context**

**Comment by c0d3r-arnab** [comment]
Hello @tinder-tder! Thank you for your feedback. Can you please try the below queries and let us know if they work for you?

**For assigned groups:**
```
select
  grp.name as name,
  jsonb_pretty(grp.profile) as group_profile
from
  okta_group grp
full outer join okta_app_assigned_group ag on grp.id = ag.id
where
  grp.id is not null and ag.id is not null;
```

**For assigned users:**
```
select
  usr.email as email,
  jsonb_pretty(usr.profile) as group_profile
from
  okta_user usr
full outer join okta_app_assigned_user au on usr.id = au.id
where
  usr.id is not null and au.id is not null;
```

**Comment by tinder-tder** [comment]
@c0d3r-arnab Thanks for checking in, Unfortunately those queries do not return the needed data.  we need the profile data from the application group assignments.  (the api call is `api/v1/apps/<appid>/groups`)

the api call returns a list that looks like:
```
[
......
  {
    "id": "xxx",
    "lastUpdated": "2021-10-13T00:02:40.000Z",
    "priority": 26,
    "profile": {
      "role": "[vvv-dev] -- alb-ingress-controller-kelkv3",
      "samlRoles": [
        "[vvv-dev-1] -- developer",
        "[vvv-dev-2] -- developer",
        "[vvv-dev-3] -- developer"
      ]
    },
    "_links": {
      "app": {
        "href": "https://vvv.okta.com/api/v1/apps/xxx"
      },
      "self": {
        "href": "https://vvv.okta.com/api/v1/apps/xxx/groups/xxx"
      },
      "group": {
        "href": "https://vvv.okta.com/api/v1/groups/xxx"
      }
    }
  }
]
```

**Comment by c0d3r-arnab** [comment]
Hello @tinder-tder!! Thank you again for the time you spent on the issue. We have added the `profile` column in the `okta_app_assigned_group` table in the PR https://github.com/turbot/steampipe-plugin-okta/pull/58. Can you please check if this works for you?

**Comment by tinder-tder** [comment]
@c0d3r-arnab Yea that change looks like it will do what we need

**Comment by rajlearner17** [comment]
@tinder-tder would it be possible to execute your query and validate the outcome? This will help to rollout this today. We could not construct the profile data and it comes as {}.

**Comment by tinder-tder** [comment]
@rajlearner17 : confirmed.  I was able to get the desired data (although I consistently see `Error: context deadline exceeded (SQLSTATE HV000)` in which retrying the query eventually works).

the query looks like:
```
select
  t1.app_id,
  t1.id as group_id,
  t2.name,
  jsonb_array_elements_text(t1.profile -> 'samlRoles') as roles
from
  okta.okta_app_assigned_group as t1,
  okta.okta_group as t2
where
  app_id = 'xxxxxxxxxxxxxxxxxxxxxx'
  AND t1.id = t2.id
```

**Comment by rajlearner17** [comment]
@tinder-tder Appreciate responding to this to close. Wired to know context cancellation one, we will take a look and roll this out today.
